#!/usr/bin/env bash

for i in $(seq 1 10); do
  echo "producing message $i"
  echo "$i:message-$i-test-topic1" | docker exec -i ziggurat_kafka /opt/bitnami/kafka/bin/kafka-console-producer.sh --broker-list "localhost:9092" --property key.separator=":" --property parse.key=true --topic "test-topic1"
  echo "$i:message-$i-test-topic2" | docker exec -i ziggurat_kafka /opt/bitnami/kafka/bin/kafka-console-producer.sh --broker-list "localhost:9092" --property key.separator=":" --property parse.key=true --topic "test-topic2"
done
