#!/usr/bin/env bash

BROKER_ADDRESS="localhost:9092"

echo "PRESS CTRL+C to terminate message production"
i=0
while true; do
  echo "producing message $i"
  ./scripts/produce_json_messages $i "$BROKER_ADDRESS"
  ./scripts/produce_text_messages $i "$BROKER_ADDRESS"
  i=$((i + 1))
  sleep 0.2s
done
