//generated by go generate
// do not edit !

package kafka

import "github.com/confluentinc/confluent-kafka-go/kafka"

type ConsumerConfig struct { 
	GroupId string 
	AutoOffsetReset string 
	EnableAutoCommit bool 
	AutoCommitIntervalMs int 
	Debug string 
	GoLogsChannelEnable bool 
	EnableAutoOffsetStore bool 
	BootstrapServers string 
	ConsumerCount int
	Topics string
	PollTimeout int
	RouteGroup string
}

func (c ConsumerConfig) toConfigMap() *kafka.ConfigMap {
    return &kafka.ConfigMap { 
        "group.id": c.GroupId, 
        "auto.offset.reset": c.AutoOffsetReset, 
        "enable.auto.commit": c.EnableAutoCommit, 
        "auto.commit.interval.ms": c.AutoCommitIntervalMs, 
        "debug": c.Debug, 
        "go.logs.channel.enable": c.GoLogsChannelEnable, 
        "enable.auto.offset.store": c.EnableAutoOffsetStore, 
        "bootstrap.servers": c.BootstrapServers, 
    }
}